project_id = "khkmhxxvspsmszpebfiz"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
refresh_token_reuse_interval = 10
enable_signup = true
enable_email_confirmations = false

[auth.email]
enable_signup = true
double_confirm_email = false

[db]
port = 54322

[edge_functions]
serve_host = "0.0.0.0"

[functions.send-unpaid-sales-notifications]
verify_jwt = false

[storage]
enabled = true
port = 54323
file_size_limit = "50MiB"
max_concurrent_uploads = 10