// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://khkmhxxvspsmszpebfiz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtoa21oeHh2c3BzbXN6cGViZml6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5NjEwNjksImV4cCI6MjA3MTUzNzA2OX0.Q9goTE3x5KqHz1MlGAqRupotLcGZP_yvz2RInLBOL9A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});